/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as CalendrierRouteImport } from './routes/calendrier'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as ConfigurationsCategoriesRouteImport } from './routes/configurations.categories'
import { Route as ActesSoinsRouteImport } from './routes/actes/soins'
import { Route as ActesProthesesRouteImport } from './routes/actes/protheses'
import { Route as ActesOrthodontieRouteImport } from './routes/actes/orthodontie'
import { Route as ActesEsthetiqueRouteImport } from './routes/actes/esthetique'
import { Route as ActesChirurgieRouteImport } from './routes/actes/chirurgie'

const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendrierRoute = CalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const ConfigurationsCategoriesRoute =
  ConfigurationsCategoriesRouteImport.update({
    id: '/configurations/categories',
    path: '/configurations/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ActesSoinsRoute = ActesSoinsRouteImport.update({
  id: '/actes/soins',
  path: '/actes/soins',
  getParentRoute: () => rootRouteImport,
} as any)
const ActesProthesesRoute = ActesProthesesRouteImport.update({
  id: '/actes/protheses',
  path: '/actes/protheses',
  getParentRoute: () => rootRouteImport,
} as any)
const ActesOrthodontieRoute = ActesOrthodontieRouteImport.update({
  id: '/actes/orthodontie',
  path: '/actes/orthodontie',
  getParentRoute: () => rootRouteImport,
} as any)
const ActesEsthetiqueRoute = ActesEsthetiqueRouteImport.update({
  id: '/actes/esthetique',
  path: '/actes/esthetique',
  getParentRoute: () => rootRouteImport,
} as any)
const ActesChirurgieRoute = ActesChirurgieRouteImport.update({
  id: '/actes/chirurgie',
  path: '/actes/chirurgie',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendrier': typeof CalendrierRoute
  '/patients': typeof PatientsRouteWithChildren
  '/rendez-vous': typeof RendezVousRoute
  '/system-status': typeof SystemStatusRoute
  '/actes/chirurgie': typeof ActesChirurgieRoute
  '/actes/esthetique': typeof ActesEsthetiqueRoute
  '/actes/orthodontie': typeof ActesOrthodontieRoute
  '/actes/protheses': typeof ActesProthesesRoute
  '/actes/soins': typeof ActesSoinsRoute
  '/configurations/categories': typeof ConfigurationsCategoriesRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendrier': typeof CalendrierRoute
  '/patients': typeof PatientsRouteWithChildren
  '/rendez-vous': typeof RendezVousRoute
  '/system-status': typeof SystemStatusRoute
  '/actes/chirurgie': typeof ActesChirurgieRoute
  '/actes/esthetique': typeof ActesEsthetiqueRoute
  '/actes/orthodontie': typeof ActesOrthodontieRoute
  '/actes/protheses': typeof ActesProthesesRoute
  '/actes/soins': typeof ActesSoinsRoute
  '/configurations/categories': typeof ConfigurationsCategoriesRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendrier': typeof CalendrierRoute
  '/patients': typeof PatientsRouteWithChildren
  '/rendez-vous': typeof RendezVousRoute
  '/system-status': typeof SystemStatusRoute
  '/actes/chirurgie': typeof ActesChirurgieRoute
  '/actes/esthetique': typeof ActesEsthetiqueRoute
  '/actes/orthodontie': typeof ActesOrthodontieRoute
  '/actes/protheses': typeof ActesProthesesRoute
  '/actes/soins': typeof ActesSoinsRoute
  '/configurations/categories': typeof ConfigurationsCategoriesRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendrier'
    | '/patients'
    | '/rendez-vous'
    | '/system-status'
    | '/actes/chirurgie'
    | '/actes/esthetique'
    | '/actes/orthodontie'
    | '/actes/protheses'
    | '/actes/soins'
    | '/configurations/categories'
    | '/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendrier'
    | '/patients'
    | '/rendez-vous'
    | '/system-status'
    | '/actes/chirurgie'
    | '/actes/esthetique'
    | '/actes/orthodontie'
    | '/actes/protheses'
    | '/actes/soins'
    | '/configurations/categories'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calendrier'
    | '/patients'
    | '/rendez-vous'
    | '/system-status'
    | '/actes/chirurgie'
    | '/actes/esthetique'
    | '/actes/orthodontie'
    | '/actes/protheses'
    | '/actes/soins'
    | '/configurations/categories'
    | '/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalendrierRoute: typeof CalendrierRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  RendezVousRoute: typeof RendezVousRoute
  SystemStatusRoute: typeof SystemStatusRoute
  ActesChirurgieRoute: typeof ActesChirurgieRoute
  ActesEsthetiqueRoute: typeof ActesEsthetiqueRoute
  ActesOrthodontieRoute: typeof ActesOrthodontieRoute
  ActesProthesesRoute: typeof ActesProthesesRoute
  ActesSoinsRoute: typeof ActesSoinsRoute
  ConfigurationsCategoriesRoute: typeof ConfigurationsCategoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendrier': {
      id: '/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof CalendrierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/configurations/categories': {
      id: '/configurations/categories'
      path: '/configurations/categories'
      fullPath: '/configurations/categories'
      preLoaderRoute: typeof ConfigurationsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actes/soins': {
      id: '/actes/soins'
      path: '/actes/soins'
      fullPath: '/actes/soins'
      preLoaderRoute: typeof ActesSoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actes/protheses': {
      id: '/actes/protheses'
      path: '/actes/protheses'
      fullPath: '/actes/protheses'
      preLoaderRoute: typeof ActesProthesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actes/orthodontie': {
      id: '/actes/orthodontie'
      path: '/actes/orthodontie'
      fullPath: '/actes/orthodontie'
      preLoaderRoute: typeof ActesOrthodontieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actes/esthetique': {
      id: '/actes/esthetique'
      path: '/actes/esthetique'
      fullPath: '/actes/esthetique'
      preLoaderRoute: typeof ActesEsthetiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actes/chirurgie': {
      id: '/actes/chirurgie'
      path: '/actes/chirurgie'
      fullPath: '/actes/chirurgie'
      preLoaderRoute: typeof ActesChirurgieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalendrierRoute: CalendrierRoute,
  PatientsRoute: PatientsRouteWithChildren,
  RendezVousRoute: RendezVousRoute,
  SystemStatusRoute: SystemStatusRoute,
  ActesChirurgieRoute: ActesChirurgieRoute,
  ActesEsthetiqueRoute: ActesEsthetiqueRoute,
  ActesOrthodontieRoute: ActesOrthodontieRoute,
  ActesProthesesRoute: ActesProthesesRoute,
  ActesSoinsRoute: ActesSoinsRoute,
  ConfigurationsCategoriesRoute: ConfigurationsCategoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
